services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - bot_volume:/app/data
    restart: unless-stopped
  redis:
    image: redis:8.2
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
volumes:
  bot_volume:
